// observation.js

/**
 * Helper to extract formatted position string from state
 */
function getFormattedPos(state) {
  if (state?.parameters?.mode === 'freefall') {
    return `${(state.position || 0).toFixed(2)} m`;
  }
  const deg = state.angleDegrees !== undefined 
    ? state.angleDegrees 
    : (state.theta ? (state.theta * 180 / Math.PI) : 0);
  return `${deg.toFixed(1)}°`;
}

/**
 * Calculates and returns real-time dynamic observation text based on current model state.
 * @param {Object} state - Current simulation state object
 * @returns {string} - Real-time situational description
 */
export function observation(state) {
  if (!state || !state.parameters) {
    return 'Ready. Select Release to start the gravity-driven oscillation.';
  }

  const posStr = getFormattedPos(state);

  if (state.parameters.mode === 'manual') {
    const absEmf = Math.abs(state.emf || 0);
    const absVel = Math.abs(state.velocity || state.omega || 0);

    if (absEmf < 0.0005) {
      return `Manual mode: Magnet stationary at ${posStr}. Since rate of flux change (dΦ/dt) is zero, induced EMF returns to zero.`;
    }

    const directionStr = state.emf > 0
      ? 'Positive EMF polarity generated by changing flux in this direction.'
      : 'Negative EMF polarity generated (opposite direction, per Lenz\'s Law).';

    return `Manual mode: Magnet at ${posStr}, dragging at ${absVel.toFixed(2)} rad/s. ${directionStr}`;
  }

  if (state.parameters.mode === 'freefall') {
    return state.running
      ? `The magnet is falling through the vertical coil guide (Position: ${posStr}). Speed and induced EMF change continuously.`
      : 'Freefall mode: select Release to drop the magnet through the coil.';
  }

  if (state.complete) {
    return 'Experiment complete. The decreasing mechanical energy has been dissipated through the resistance of the measurement circuit and pivot losses.';
  }

  if (!state.running) {
    return `Ready at ${posStr}. Select Release to start the gravity-driven oscillation.`;
  }

  if (Math.abs(state.emf) < 0.0005) {
    return `Near turning point (${posStr}), the magnet is momentarily slow, so flux change (dΦ/dt) and induced EMF approach zero.`;
  }

  return state.emf > 0
    ? `At ${posStr}: coil polarity is positive for this direction of changing flux.`
    : `At ${posStr}: changing flux induces opposite polarity per Faraday's and Lenz's laws.`;
}

/**
 * Returns HTML string for the Lab Reference section.
 * @returns {string} HTML string
 */
export function getLabReferenceHTML() {
  return `
    <div class="sidebar-card-content" style="padding: 12px; font-size: 0.88em; line-height: 1.5;">
      <h3 style="margin-top:0; color:#168983; font-size: 1.05em; border-bottom: 2px solid #e0e0e0; padding-bottom: 6px;">Lab Reference</h3>
      <ul style="list-style: none; padding: 0; margin: 8px 0 16px 0;">
        <li style="margin-bottom: 6px;"><strong>Polarity Rule:</strong> Lenz's Law</li>
        <li style="margin-bottom: 6px;"><strong>Diode Threshold:</strong> 0.7 V</li>
        <li style="margin-bottom: 6px;"><strong>Peak Holding:</strong> Capacitor C</li>
        <li style="margin-bottom: 6px;"><strong>Noise Threshold:</strong> &lt; 0.5 mV</li>
      </ul>
    </div>
  `;
}

/**
 * Returns HTML string for the Situational Observations collapsible accordion.
 * @returns {string} HTML string
 */
export function getSituationalObservationsHTML() {
  return `
    <details class="situational-observations-accordion" style="background: #ffffff; border: 1px solid #dce7e6; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.05); overflow: hidden; margin-top: 10px;" >
      <summary style="padding: 10px 12px; color: #168983; font-weight: bold; font-size: 0.95em; cursor: pointer !important; user-select: none; display: flex; justify-content: space-between; align-items: center; list-style: none; background: #f4f8f8;">
        <span>Situational Observations</span>
        <span style="font-size: 0.8em; color: #168983; display: inline-block;">▼</span>
      </summary>
      
      <div style="display: flex; flex-direction: column; gap: 8px; padding: 12px; border-top: 1px solid #dce7e6; background: #fafcfc;">
        <div style="background: #ffffff; padding: 8px; border-radius: 6px; border-left: 3px solid #168983; box-shadow: 0 1px 2px rgba(0,0,0,0.03);">
          <strong style="color: #168983; font-size: 0.9em;">1. Initial State / Ready</strong>
          <p style="margin: 4px 0 0 0; color: #405150; font-size: 0.85em;">Ready. Select Release to start the gravity-driven oscillation.</p>
        </div>

        <div style="background: #ffffff; padding: 8px; border-radius: 6px; border-left: 3px solid #168983; box-shadow: 0 1px 2px rgba(0,0,0,0.03);">
          <strong style="color: #168983; font-size: 0.9em;">2. Manual Mode</strong>
          <p style="margin: 4px 0 0 0; color: #405150; font-size: 0.85em;">Move the magnet frame and observe how a changing flux produces an EMF. Hold still and EMF returns to zero.</p>
        </div>

        <div style="background: #ffffff; padding: 8px; border-radius: 6px; border-left: 3px solid #168983; box-shadow: 0 1px 2px rgba(0,0,0,0.03);">
          <strong style="color: #168983; font-size: 0.9em;">3. Freefall Mode</strong>
          <p style="margin: 4px 0 0 0; color: #405150; font-size: 0.85em;">The magnet falls vertically through the coil under gravity. Speed and induced EMF change continuously.</p>
        </div>

        <div style="background: #ffffff; padding: 8px; border-radius: 6px; border-left: 3px solid #168983; box-shadow: 0 1px 2px rgba(0,0,0,0.03);">
          <strong style="color: #168983; font-size: 0.9em;">4. Turning Point (Slow Motion)</strong>
          <p style="margin: 4px 0 0 0; color: #405150; font-size: 0.85em;">Near turning points, the magnet slows down, so the rate of change of flux (dΦ/dt) and induced EMF approach zero.</p>
        </div>

        <div style="background: #ffffff; padding: 8px; border-radius: 6px; border-left: 3px solid #168983; box-shadow: 0 1px 2px rgba(0,0,0,0.03);">
          <strong style="color: #168983; font-size: 0.9em;">5. Direction & Polarity</strong>
          <p style="margin: 4px 0 0 0; color: #405150; font-size: 0.85em;">Positive/negative EMF indicates flux direction; reversing motion or magnet poles reverses induced voltage polarity (Lenz's Law).</p>
        </div>

        <div style="background: #ffffff; padding: 8px; border-radius: 6px; border-left: 3px solid #168983; box-shadow: 0 1px 2px rgba(0,0,0,0.03);">
          <strong style="color: #168983; font-size: 0.9em;">6. Experiment Complete</strong>
          <p style="margin: 4px 0 0 0; color: #405150; font-size: 0.85em;">Decreasing mechanical energy is dissipated as electrical energy through circuit resistance and mechanical pivot friction.</p>
        </div>
      </div>
    </details>
  `;
}

/**
 * Helper to render both Lab Reference and Situational Observations into a sidebar container.
 * @param {HTMLElement} containerEl Target sidebar element
 */
export function renderObservationSidebar(containerEl) {
  if (!containerEl) return;
  containerEl.innerHTML = `
    ${getLabReferenceHTML()}
    ${getSituationalObservationsHTML()}
  `;
}