const $ = (selector) => document.querySelector(selector);
const model = new InductionModel();
const apparatus = $('#apparatusCanvas'); const apparatusContext = apparatus.getContext('2d');
const emfGraph = $('#emfGraph'); const angleGraph = $('#angleGraph');
const elements = { status:$('#experimentStatus'), dot:$('#statusDot'), meter:$('#voltmeter'), polarity:$('#polarityText'), angle:$('#angleValue'), velocity:$('#velocityValue'), flux:$('#fluxValue'), emf:$('#emfValue'), count:$('#countValue'), motion:$('#motionValue'), observation:$('#observationText'), release:$('#releaseButton'), pause:$('#pauseButton'), reset:$('#resetButton'), railPlay:$('#railPlayButton'), railLabel:$('#railPlayLabel'), graphs:$('#graphs') };
const controls = [{ name:'angle', input:$('#angleControl'), output:$('#angleOutput'), format:v=>`${v}°` }, { name:'turns', input:$('#turnsControl'), output:$('#turnsOutput'), format:v=>v }, { name:'strength', input:$('#strengthControl'), output:$('#strengthOutput'), format:v=>`${Number(v).toFixed(1)} T` }, { name:'damping', input:$('#dampingControl'), output:$('#dampingOutput'), format:v=>Number(v).toFixed(2) }, { name:'speed', input:$('#speedControl'), output:$('#speedOutput'), format:v=>`${Number(v).toFixed(1)}×` }];
controls.forEach(({name,input,output,format}) => input.addEventListener('input', () => { const value = Number(input.value); output.textContent = format(value); model.setParameter(name, value); sync(model.state); }));

function resizeCanvas(canvas, context) { const rect = canvas.getBoundingClientRect(); const ratio = window.devicePixelRatio || 1; const width = Math.round(rect.width * ratio); const height = Math.round(rect.height * ratio); if (canvas.width !== width || canvas.height !== height) { canvas.width = width; canvas.height = height; context.setTransform(ratio, 0, 0, ratio, 0, 0); } return rect; }
function line(context, points, color, width=2) { context.beginPath(); points.forEach(([x,y], index) => index ? context.lineTo(x,y) : context.moveTo(x,y)); context.strokeStyle=color; context.lineWidth=width; context.stroke(); }
function arrow(context, x1,y1,x2,y2,color) { line(context,[[x1,y1],[x2,y2]],color,2); const angle=Math.atan2(y2-y1,x2-x1); context.beginPath(); context.moveTo(x2,y2); context.lineTo(x2-8*Math.cos(angle-.45),y2-8*Math.sin(angle-.45)); context.lineTo(x2-8*Math.cos(angle+.45),y2-8*Math.sin(angle+.45)); context.closePath(); context.fillStyle=color; context.fill(); }
function drawApparatus(state) { const {width,height}=resizeCanvas(apparatus,apparatusContext); const c=apparatusContext; c.clearRect(0,0,width,height); const scale=Math.min(width/620,height/370); const ox=(width-620*scale)/2, oy=(height-370*scale)/2; c.save(); c.translate(ox,oy); c.scale(scale,scale);
  c.fillStyle='#e8f4f3'; c.fillRect(0,0,620,370); c.strokeStyle='#b5caca'; c.lineWidth=1; for(let x=30;x<620;x+=40) line(c,[[x,315],[x+18,315]],'#d8e6e5',1);
  c.fillStyle='#697372'; c.fillRect(80,287,235,12); c.fillStyle='#879190'; c.fillRect(95,300,205,8); c.fillStyle='#596160'; c.fillRect(166,88,11,200); c.fillStyle='#737c7b'; c.fillRect(146,75,50,12); c.beginPath(); c.arc(171.5,93,12,0,Math.PI*2); c.fillStyle='#3d4746'; c.fill(); c.beginPath(); c.arc(171.5,93,5,0,Math.PI*2); c.fillStyle='#d9dedc'; c.fill();
  const arm=180, pivot={x:171.5,y:93}; const direction=Math.PI/2+state.theta; const magnet={x:pivot.x+arm*Math.cos(direction),y:pivot.y+arm*Math.sin(direction)}; c.beginPath(); c.arc(pivot.x,pivot.y,arm,Math.PI/2-.98,Math.PI/2+.98); c.strokeStyle='#6d7775'; c.lineWidth=8; c.stroke(); c.beginPath(); c.arc(pivot.x,pivot.y,arm,Math.PI/2-.98,Math.PI/2+.98); c.strokeStyle='#aeb6b4'; c.lineWidth=3; c.stroke(); line(c,[[pivot.x,pivot.y],[magnet.x,magnet.y]],'#4f5957',6);
  c.save(); c.translate(magnet.x,magnet.y); c.rotate(direction); c.fillStyle='#b93c36'; c.fillRect(-30,-14,30,28); c.fillStyle='#397ca8'; c.fillRect(0,-14,30,28); c.strokeStyle='#404a4a'; c.lineWidth=2; c.strokeRect(-30,-14,60,28); c.fillStyle='#fff'; c.font='700 11px Nunito'; c.fillText('N',-21,4); c.fillText('S',17,4); c.restore();
  const coilX=435, coilY=266; c.fillStyle='#565f5e'; c.fillRect(403,286,65,8); c.fillRect(416,212,9,77); for(let i=0;i<8;i++){c.beginPath(); c.ellipse(coilX,251,28-i*.3,43-i*.3,0,0,Math.PI*2); c.strokeStyle='#bd7025'; c.lineWidth=3; c.stroke();} c.fillStyle='#586260'; c.fillRect(427,200,16,12); c.fillStyle='#697372'; c.fillRect(429,194,12,8);
  const emfMagnitude=Math.min(Math.abs(state.emf)*18,1); c.globalAlpha=.18+.55*emfMagnitude; for(let i=0;i<3;i++){c.beginPath(); c.ellipse(coilX,251,42+i*13,57+i*16,0,0,Math.PI*2); c.strokeStyle='#db8b22'; c.lineWidth=1; c.stroke();} c.globalAlpha=1;
  const polarity=state.emf>=0?1:-1; arrow(c,465,218,525,205,polarity>0?'#168983':'#b54747'); arrow(c,468,280,530,295,polarity>0?'#168983':'#b54747'); line(c,[[465,217],[492,178],[545,178]],'#3b5554',2); line(c,[[469,280],[496,319],[545,319]],'#3b5554',2); c.fillStyle='#f8f8f4'; c.strokeStyle='#687574'; c.lineWidth=2; c.fillRect(540,160,66,176); c.strokeRect(540,160,66,176); c.fillStyle='#3a4342'; c.fillRect(550,184,46,24); c.fillStyle='#efff9b'; c.font='bold 12px monospace'; c.fillText(`${state.emf>=0?'+':''}${state.emf.toFixed(2)}`,553,201); c.fillStyle='#485250'; c.font='600 10px Nunito'; c.fillText('VOLTMETER',547,225); c.beginPath(); c.arc(557,303,5,0,Math.PI*2); c.fillStyle='#b34747'; c.fill(); c.beginPath(); c.arc(587,303,5,0,Math.PI*2); c.fillStyle='#315788'; c.fill();
  c.fillStyle='#556160'; c.font='600 11px Nunito'; c.fillText('Copper coil',407,346); c.fillText('Semicircular frame',89,50); c.restore(); }
function drawGraph(canvas, color, data, accessor, min, max) { const c=canvas.getContext('2d'); const {width,height}=resizeCanvas(canvas,c); c.clearRect(0,0,width,height); const pad={left:35,right:10,top:12,bottom:27}; const pw=width-pad.left-pad.right, ph=height-pad.top-pad.bottom; c.font='11px Nunito'; c.strokeStyle='#d8e3e3'; c.lineWidth=1; for(let i=0;i<5;i++){const y=pad.top+i*ph/4; line(c,[[pad.left,y],[width-pad.right,y]],'#e2ebeb',1);} line(c,[[pad.left,pad.top],[pad.left,height-pad.bottom],[width-pad.right,height-pad.bottom]],'#607170',1); c.fillStyle='#627070'; c.fillText(max.toFixed(2),2,pad.top+4); c.fillText(min.toFixed(2),2,height-pad.bottom+4); c.fillText('time →',width/2-17,height-7); if(data.length<2)return; const t0=data[0].time,t1=data[data.length-1].time||1; c.beginPath(); data.forEach((point,index)=>{const x=pad.left+(point.time-t0)/(t1-t0)*pw; const value=Math.max(min,Math.min(max,accessor(point))); const y=pad.top+(max-value)/(max-min)*ph; index?c.lineTo(x,y):c.moveTo(x,y);}); c.strokeStyle=color;c.lineWidth=2;c.stroke(); }
function observation(state) { if(state.complete) return 'Experiment complete. The frame has come to rest as induced current opposed the changing flux.'; if(!state.running) return state.time>0?'Paused. Resume to continue observing the induced EMF.':'Set an initial angle, then release the frame to begin the experiment.'; if(Math.abs(state.emf)<.002) return 'At the turning point, the magnet is momentarily slow and induced EMF is nearly zero.'; return state.emf>0?'Magnet motion is increasing flux through the coil. A positive EMF is generated; induced current opposes this change.':'Magnet motion is decreasing flux through the coil. EMF polarity reverses, opposing the changing flux.'; }
function sync(state) { const sign=state.emf>=0?'+':''; elements.meter.textContent=`${sign}${state.emf.toFixed(3)} V`; elements.angle.textContent=`${state.angleDegrees.toFixed(1)}°`; elements.velocity.textContent=`${state.velocity.toFixed(3)} rad/s`; elements.flux.textContent=`${state.fluxMilliWebers.toFixed(3)} mWb`; elements.emf.textContent=`${sign}${state.emf.toFixed(3)} V`; elements.count.textContent=state.oscillations; elements.motion.textContent=Math.abs(state.velocity)<.006?'Stationary':state.velocity>0?'Clockwise':'Counter-clockwise'; elements.polarity.textContent=Math.abs(state.emf)<.002?'No induced EMF':state.emf>0?'Positive EMF':'Negative EMF'; elements.observation.textContent=observation(state); elements.status.textContent=state.complete?'Experiment complete':state.running?'Oscillating':'Paused'; if(state.time===0&&!state.running) elements.status.textContent='Ready to release'; elements.dot.className=`status-dot ${state.running?'running':state.time>0?'paused':''}`; elements.pause.textContent=state.running?'Pause':'Resume'; elements.release.disabled=state.running; elements.railPlay.className=`rail-button icon-play ${state.running?'is-paused':''}`; elements.railLabel.textContent=state.running?'Pause':'Start'; drawApparatus(state); drawGraph(emfGraph,'#168983',state.history,p=>p.emf,-.18,.18); drawGraph(angleGraph,'#b36d24',state.history,p=>p.angle,-60,60); }
function release(){model.release();sync(model.state);} function toggle(){model.running?model.pause():model.release();sync(model.state);} function reset(){model.reset();sync(model.state);}
elements.release.addEventListener('click',release); elements.pause.addEventListener('click',toggle); elements.reset.addEventListener('click',reset); elements.railPlay.addEventListener('click',toggle); $('#railGraphButton').addEventListener('click',()=>{elements.graphs.classList.toggle('is-hidden'); if(!elements.graphs.classList.contains('is-hidden')){elements.graphs.scrollIntoView({behavior:'smooth',block:'nearest'});sync(model.state);}}); window.addEventListener('resize',()=>sync(model.state));
let last=performance.now(); function animate(now){model.update((now-last)/1000);last=now;sync(model.state);requestAnimationFrame(animate);} sync(model.state);requestAnimationFrame(animate);
