const $ = (selector) => document.querySelector(selector);
const model = new InductionModel();
const apparatus = $('#apparatusCanvas'); const apparatusContext = apparatus.getContext('2d'); let isDragging = false; let hasDragged = false;
const emfGraph = $('#emfGraph'); const angleGraph = $('#angleGraph');
const elements = { status: $('#experimentStatus'), dot: $('#statusDot'), meter: $('#voltmeter'), polarity: $('#polarityText'), angle: $('#angleValue'), velocity: $('#velocityValue'), flux: $('#fluxValue'), emf: $('#emfValue'), count: $('#countValue'), motion: $('#motionValue'), observation: $('#observationText'), release: $('#releaseButton'), pause: $('#pauseButton'), reset: $('#resetButton'), graphs: $('#graphs'), heat: $('#heatValue'), heatFill: $('#heatFill'), readings: $('#emfReadings'), dragHint: $('#dragHint') };
const controls = [{ name: 'angle', input: $('#angleControl'), output: $('#angleOutput'), format: v => `${v}°` }, { name: 'turns', input: $('#turnsControl'), output: $('#turnsOutput'), format: v => v }, { name: 'strength', input: $('#strengthControl'), output: $('#strengthOutput'), format: v => `${Number(v).toFixed(1)} T` }, { name: 'damping', input: $('#dampingControl'), output: $('#dampingOutput'), format: v => Number(v).toFixed(2) }, { name: 'speed', input: $('#speedControl'), output: $('#speedOutput'), format: v => `${Number(v).toFixed(1)}×` }];
controls.forEach(({ name, input, output, format }) => input.addEventListener('input', () => { const value = Number(input.value); output.textContent = format(value); model.setParameter(name, value); sync(model.state); }));

function resizeCanvas(canvas, context) { const rect = canvas.getBoundingClientRect(); const ratio = window.devicePixelRatio || 1; const width = Math.round(rect.width * ratio); const height = Math.round(rect.height * ratio); if (canvas.width !== width || canvas.height !== height) { canvas.width = width; canvas.height = height; context.setTransform(ratio, 0, 0, ratio, 0, 0); } return rect; }
function line(context, points, color, width = 2) { context.beginPath(); points.forEach(([x, y], index) => index ? context.lineTo(x, y) : context.moveTo(x, y)); context.strokeStyle = color; context.lineWidth = width; context.stroke(); }
function arrow(context, x1, y1, x2, y2, color) { line(context, [[x1, y1], [x2, y2]], color, 2); const angle = Math.atan2(y2 - y1, x2 - x1); context.beginPath(); context.moveTo(x2, y2); context.lineTo(x2 - 8 * Math.cos(angle - .45), y2 - 8 * Math.sin(angle - .45)); context.lineTo(x2 - 8 * Math.cos(angle + .45), y2 - 8 * Math.sin(angle + .45)); context.closePath(); context.fillStyle = color; context.fill(); }
function drawApparatus(state) {
  const { width, height } = resizeCanvas(apparatus, apparatusContext); const c = apparatusContext; c.clearRect(0, 0, width, height);
  const meterPanel = $('.meter-panel'); const meterSpace = window.matchMedia('(min-width: 761px)').matches && meterPanel ? meterPanel.offsetWidth + 32 : 0;
  const drawingWidth = Math.max(280, width - meterSpace); const scale = Math.min(drawingWidth / 620, height / 370); const ox = (drawingWidth - 620 * scale) / 2, oy = (height - 370 * scale) / 2; c.save(); c.translate(ox, oy); c.scale(scale, scale);
  c.fillStyle = '#ffffff'; c.fillRect(0, 0, 620, 370); c.strokeStyle = '#e2e8f0'; c.lineWidth = 1; for (let x = 30; x < 620; x += 40) line(c, [[x, 315], [x + 18, 315]], '#f1f5f9', 1);
  c.fillStyle = '#697372'; c.fillRect(80, 287, 235, 12); c.fillStyle = '#879190'; c.fillRect(95, 300, 205, 8); c.fillStyle = '#596160'; c.fillRect(166, 88, 11, 200); c.fillStyle = '#737c7b'; c.fillRect(146, 75, 50, 12); c.beginPath(); c.arc(171.5, 93, 12, 0, Math.PI * 2); c.fillStyle = '#3d4746'; c.fill(); c.beginPath(); c.arc(171.5, 93, 5, 0, Math.PI * 2); c.fillStyle = '#d9dedc'; c.fill();
  const arm = 180, pivot = { x: 171.5, y: 93 }; const direction = Math.PI / 2 + state.theta; const magnet = { x: pivot.x + arm * Math.cos(direction), y: pivot.y + arm * Math.sin(direction) }; c.beginPath(); c.arc(pivot.x, pivot.y, arm, Math.PI / 2 - .98, Math.PI / 2 + .98); c.strokeStyle = '#6d7775'; c.lineWidth = 8; c.stroke(); c.beginPath(); c.arc(pivot.x, pivot.y, arm, Math.PI / 2 - .98, Math.PI / 2 + .98); c.strokeStyle = '#aeb6b4'; c.lineWidth = 3; c.stroke(); line(c, [[pivot.x, pivot.y], [magnet.x, magnet.y]], '#4f5957', 6);
  c.save(); c.translate(magnet.x, magnet.y); c.rotate(direction); c.fillStyle = '#b93c36'; c.fillRect(-30, -14, 30, 28); c.fillStyle = '#397ca8'; c.fillRect(0, -14, 30, 28); c.strokeStyle = '#404a4a'; c.lineWidth = 2; c.strokeRect(-30, -14, 60, 28); c.fillStyle = '#fff'; c.font = '700 11px Nunito'; c.fillText('N', -21, 4); c.fillText('S', 17, 4); c.restore();
  const coilX = 435, coilY = 266; c.fillStyle = '#565f5e'; c.fillRect(403, 286, 65, 8); c.fillRect(416, 212, 9, 77); for (let i = 0; i < 8; i++) { c.beginPath(); c.ellipse(coilX, 251, 28 - i * .3, 43 - i * .3, 0, 0, Math.PI * 2); c.strokeStyle = '#bd7025'; c.lineWidth = 3; c.stroke(); } c.fillStyle = '#586260'; c.fillRect(427, 200, 16, 12); c.fillStyle = '#697372'; c.fillRect(429, 194, 12, 8);
  const emfMagnitude = Math.min(Math.abs(state.emf) * 18, 1); c.globalAlpha = .18 + .55 * emfMagnitude; for (let i = 0; i < 3; i++) { c.beginPath(); c.ellipse(coilX, 251, 42 + i * 13, 57 + i * 16, 0, 0, Math.PI * 2); c.strokeStyle = '#db8b22'; c.lineWidth = 1; c.stroke(); } c.globalAlpha = 1;
  const polarity = state.emf >= 0 ? 1 : -1; arrow(c, 465, 218, 510, 155, polarity > 0 ? '#168983' : '#b54747'); arrow(c, 468, 280, 520, 215, polarity > 0 ? '#168983' : '#b54747'); line(c, [[465, 217], [495, 130], [525, 25]], '#3b5554', 2); line(c, [[469, 280], [515, 170], [555, 25]], '#3b5554', 2); c.beginPath(); c.arc(525, 25, 4, 0, Math.PI * 2); c.fillStyle = '#b34747'; c.fill(); c.beginPath(); c.arc(555, 25, 4, 0, Math.PI * 2); c.fillStyle = '#315788'; c.fill();
  c.fillStyle = '#556160'; c.font = '600 11px Nunito'; c.fillText('Copper coil', 407, 346); c.textAlign = 'center'; c.fillText('Semicircular frame', 171.5, 50); c.textAlign = 'left'; c.restore();
}
function drawGraph(canvas, color, data, accessor, min, max) { const c = canvas.getContext('2d'); const { width, height } = resizeCanvas(canvas, c); c.clearRect(0, 0, width, height); const pad = { left: 35, right: 10, top: 12, bottom: 27 }; const pw = width - pad.left - pad.right, ph = height - pad.top - pad.bottom; c.font = '11px Nunito'; c.strokeStyle = '#d8e3e3'; c.lineWidth = 1; for (let i = 0; i < 5; i++) { const y = pad.top + i * ph / 4; line(c, [[pad.left, y], [width - pad.right, y]], '#e2ebeb', 1); } line(c, [[pad.left, pad.top], [pad.left, height - pad.bottom], [width - pad.right, height - pad.bottom]], '#607170', 1); c.fillStyle = '#627070'; c.fillText(max.toFixed(2), 2, pad.top + 4); c.fillText(min.toFixed(2), 2, height - pad.bottom + 4); c.fillText('time →', width / 2 - 17, height - 7); if (data.length < 2) return; const t0 = data[0].time, t1 = data[data.length - 1].time || 1; c.beginPath(); data.forEach((point, index) => { const x = pad.left + (point.time - t0) / (t1 - t0) * pw; const value = Math.max(min, Math.min(max, accessor(point))); const y = pad.top + (max - value) / (max - min) * ph; index ? c.lineTo(x, y) : c.moveTo(x, y); }); c.strokeStyle = color; c.lineWidth = 2; c.stroke(); }
function observation(state) { if (state.complete) return 'Experiment complete. Mechanical energy was converted to electrical energy and dissipated as heat in the coil; Lenz’s law damped the motion.'; if (!state.running) return state.time > 0 ? 'Paused. Resume to continue observing the induced EMF.' : hasDragged ? 'Frame displaced. Release it gently to start free oscillation.' : 'Drag the semicircular frame to one side, then release it to begin the experiment.'; if (Math.abs(state.emf) < .002) return 'At the turning point the magnet is momentarily slow, so the induced EMF is nearly zero.'; return state.emf > 0 ? 'Magnet is moving toward the coil: flux increases and a positive EMF is generated.' : 'Magnet is moving away from the coil: flux decreases and the EMF reverses.'; }
function sync(state) { const sign = state.emf >= 0 ? '+' : ''; elements.meter.textContent = `${sign}${state.emf.toFixed(3)} V`; elements.angle.textContent = `${state.angleDegrees.toFixed(1)}°`; elements.velocity.textContent = `${state.velocity.toFixed(3)} rad/s`; elements.flux.textContent = `${state.fluxMilliWebers.toFixed(3)} mWb`; elements.emf.textContent = `${sign}${state.emf.toFixed(3)} V`; elements.count.textContent = state.oscillations; elements.motion.textContent = Math.abs(state.velocity) < .006 ? 'Stationary' : state.velocity > 0 ? 'Clockwise' : 'Counter-clockwise'; elements.polarity.textContent = Math.abs(state.emf) < .002 ? 'No induced EMF' : state.emf > 0 ? 'Positive EMF' : 'Negative EMF'; elements.observation.textContent = observation(state); elements.status.textContent = state.complete ? 'Experiment complete' : state.running ? 'Oscillating' : 'Paused'; if (state.time === 0 && !state.running) elements.status.textContent = hasDragged ? 'Frame displaced — ready to release' : 'Drag frame to set initial displacement'; elements.dot.className = `status-dot ${state.running ? 'running' : state.time > 0 ? 'paused' : ''}`; elements.pause.textContent = state.running ? 'Pause' : 'Resume'; elements.release.disabled = state.running; elements.dragHint.hidden = state.running || hasDragged; elements.heat.textContent = `${(state.electricalEnergy * 1000).toFixed(3)} mJ`; elements.heatFill.style.width = `${Math.min(state.electricalEnergy * 8000, 100)}%`; elements.readings.innerHTML = state.readings.length ? state.readings.map((reading, index) => `<tr><td>${index + 1}</td><td>${reading.time.toFixed(2)} s</td><td class="${reading.emf > 0 ? 'positive-reading' : 'negative-reading'}">${reading.emf > 0 ? '+' : ''}${reading.emf.toFixed(3)} V</td></tr>`).join('') : '<tr><td colspan="3">Release the frame to record readings.</td></tr>'; drawApparatus(state); drawGraph(emfGraph, '#168983', state.history, p => p.emf, -.18, .18); drawGraph(angleGraph, '#b36d24', state.history, p => p.angle, -60, 60); }
function release() { model.release(); sync(model.state); } function toggle() { model.running ? model.pause() : model.release(); sync(model.state); } function reset() { model.reset(); sync(model.state); }
function dragFrame(event) { if (!isDragging || model.running) return; const rect = apparatus.getBoundingClientRect(); const x = (event.clientX - rect.left) / rect.width * 620; const y = (event.clientY - rect.top) / rect.height * 370; const pivot = { x: 171.5, y: 93 }; let angle = Math.atan2(y - pivot.y, x - pivot.x) - Math.PI / 2; angle = Math.max(-55 * Math.PI / 180, Math.min(55 * Math.PI / 180, angle)); const magnitude = Math.round(Math.abs(angle * 180 / Math.PI)); $('#angleControl').value = magnitude; $('#angleOutput').textContent = `${magnitude}°`; model.setParameter('angle', magnitude); model.theta = angle; model.omega = 0; model.updateElectromagnetism(); hasDragged = true; sync(model.state); }
apparatus.addEventListener('pointerdown', (event) => { if (model.running) return; isDragging = true; apparatus.setPointerCapture(event.pointerId); dragFrame(event); }); apparatus.addEventListener('pointermove', dragFrame); apparatus.addEventListener('pointerup', () => { isDragging = false; }); apparatus.addEventListener('pointercancel', () => { isDragging = false; });
elements.release.addEventListener('click', release); elements.pause.addEventListener('click', toggle); elements.reset.addEventListener('click', () => { hasDragged = false; reset(); });
const workspaceViewport = $('#workspaceViewport'), workspaceTitle = $('#workspaceTitle'), simulationCard = $('#simulation'), controlsLockButton = $('#controlsLockButton');
const sectionList = document.createElement('div'); sectionList.id = 'sectionList'; sectionList.className = 'section-list';
const mainSection = document.querySelector('.main-section'); const footer = mainSection.querySelector('.footer'); mainSection.insertBefore(sectionList, footer);
const simulationWindow = $('#simulationWindow');
const sectionNames = { simulation: 'Simulation', diagram: 'Diagram', formula: 'Formula', calculation: 'Calculation', graphs: 'Live Graphs', results: 'Results', observation: 'Observation', experiments: 'Experiments' };
const workspaceSections = {
  simulation: simulationWindow, diagram: $('#diagram'), formula: $('#formula'), calculation: $('#calculation'), graphs: $('#graphs'), results: $('#observations'), observation: $('#observation'), experiments: $('#experiments')
};
Object.entries(workspaceSections).forEach(([name, section]) => { if (!section || name === 'simulation') return; sectionList.append(section); });
simulationWindow.classList.add('workspace-section', 'simulation-window');
simulationWindow.classList.add('is-active-workspace');
let workspaceMode = 'simulation', controlsLocked = false;
function refreshControlState() { const canUseVariables = true; const canUseToolbar = true; controls.forEach(control => { control.input.disabled = !canUseVariables || (controlsLocked && model.running); }); controlsLockButton.disabled = !canUseVariables; elements.release.disabled = !canUseToolbar || model.running; elements.pause.disabled = !canUseToolbar; elements.reset.disabled = !canUseToolbar; $('#helpButton').disabled = !canUseToolbar; }
controlsLockButton.addEventListener('click', event => { event.preventDefault(); event.stopPropagation(); controlsLocked = !controlsLocked; controlsLockButton.classList.toggle('is-locked', controlsLocked); controlsLockButton.setAttribute('aria-pressed', String(controlsLocked)); controlsLockButton.textContent = controlsLocked ? '🔒 Locked' : '🔓 Lock'; refreshControlState(); });
function selectWorkspace(name) {
  const nextSection = workspaceSections[name]; if (!nextSection || name === workspaceMode) return;
  const currentSection = workspaceSections[workspaceMode];
  currentSection.classList.remove('is-active-workspace');
  sectionList.append(currentSection);
  if (nextSection.tagName === 'DETAILS') nextSection.open = true;
  workspaceViewport.append(nextSection);
  nextSection.classList.add('is-active-workspace');
  workspaceMode = name;
  document.querySelectorAll('.workspace-link').forEach(link => link.classList.toggle('is-active', link.dataset.workspace === name));
  workspaceTitle.textContent = sectionNames[name];
  simulationCard.classList.toggle('is-reference-mode', name !== 'simulation');
  simulationCard.classList.toggle('is-graph-mode', name === 'graphs');
  refreshControlState();
  sync(model.state);
}
document.querySelectorAll('.workspace-link').forEach(link => link.addEventListener('click', () => selectWorkspace(link.dataset.workspace)));
function syncWorkspaceGraphs() { if (workspaceMode !== 'graphs') return; const canvases = workspaceViewport.querySelectorAll('canvas'); if (canvases.length === 2) { drawGraph(canvases[0], '#168983', model.state.history, point => point.emf, -.18, .18); drawGraph(canvases[1], '#b36d24', model.state.history, point => point.angle, -60, 60); } }
const fullscreenButton = $('#fullscreenButton');
fullscreenButton.addEventListener('click', async () => { try { if (document.fullscreenElement) await document.exitFullscreen(); else await document.documentElement.requestFullscreen(); } catch (_) {} });
document.addEventListener('fullscreenchange', () => { const isFullscreen = Boolean(document.fullscreenElement); fullscreenButton.textContent = isFullscreen ? '⊡' : '⛶'; fullscreenButton.setAttribute('aria-label', isFullscreen ? 'Exit website fullscreen' : 'View website fullscreen'); fullscreenButton.title = isFullscreen ? 'Exit fullscreen' : 'Fullscreen'; });
const helpOverlay = $('#helpOverlay'), helpPopover = $('#helpPopover'), helpText = $('#helpText'), helpStep = $('#helpStep'), nextHelpButton = $('#nextHelpButton'); let helpIndex = 0;
const helpItems = [
  { target: '#releaseButton', title: 'Release the frame', text: 'After dragging the frame to an initial angle, select Release to start free oscillation. The changing magnetic flux produces the induced EMF.' },
  { target: '#pauseButton', title: 'Pause or resume', text: 'Pause freezes the motion so you can inspect the meter and results. Select Resume to continue from the same point.' },
  { target: '#resetButton', title: 'Reset the trial', text: 'Reset clears the motion, graph history and readings, returning the apparatus to its starting state.' },
  { target: '#angleControl', title: 'Initial angle', text: 'This sets the starting displacement. A larger angle generally makes the magnet move faster and increases the peak induced EMF.' },
  { target: '#turnsControl', title: 'Coil turns', text: 'Increasing the number of turns increases the induced EMF because more turns experience the changing magnetic flux.' },
  { target: '#strengthControl', title: 'Magnet strength', text: 'A stronger magnet creates a larger magnetic flux, so a change in position generates a larger EMF.' },
  { target: '#dampingControl', title: 'Damping factor', text: 'Higher damping removes energy more quickly, causing the oscillations and induced EMF to fade sooner.' },
  { target: '#speedControl', title: 'Simulation speed', text: 'This changes only how quickly the simulation plays on screen; it does not change the experiment parameters.' }
];
function placeHelp() { const item = helpItems[helpIndex], target = $(item.target); document.querySelectorAll('.help-highlight').forEach(el => el.classList.remove('help-highlight')); target.classList.add('help-highlight'); const rect = target.getBoundingClientRect(); const popoverHeight = helpPopover.offsetHeight || 210; let top = rect.bottom + 18, left = Math.max(18, Math.min(window.innerWidth - helpPopover.offsetWidth - 18, rect.left)); if (top + popoverHeight > window.innerHeight - 18) top = Math.max(18, rect.top - popoverHeight - 18); helpPopover.style.top = `${top}px`; helpPopover.style.left = `${left}px`; }
function showHelpItem() { const item = helpItems[helpIndex]; const target = $(item.target); const containingSection = target.closest('details'); if (containingSection) containingSection.open = true; $('#helpTitle').textContent = item.title; helpText.textContent = item.text; helpStep.textContent = `Guide ${helpIndex + 1} of ${helpItems.length}`; nextHelpButton.textContent = helpIndex === helpItems.length - 1 ? 'Finish' : 'Next'; requestAnimationFrame(placeHelp); }
function closeHelp() { helpOverlay.hidden = true; helpOverlay.setAttribute('aria-hidden', 'true'); document.querySelectorAll('.help-highlight').forEach(el => el.classList.remove('help-highlight')); }
$('#helpButton').addEventListener('click', () => { if (workspaceMode !== 'simulation') return; helpIndex = 0; helpOverlay.hidden = false; helpOverlay.setAttribute('aria-hidden', 'false'); showHelpItem(); }); nextHelpButton.addEventListener('click', () => { if (helpIndex === helpItems.length - 1) closeHelp(); else { helpIndex += 1; showHelpItem(); } }); $('#closeHelpButton').addEventListener('click', closeHelp); helpOverlay.addEventListener('click', event => { if (event.target === helpOverlay) closeHelp(); }); window.addEventListener('resize', () => { if (!helpOverlay.hidden) placeHelp(); });

let draggedCard = null; document.querySelectorAll('.reference-card, .graphs-card').forEach(card => { card.setAttribute('draggable', 'true'); card.addEventListener('dragstart', event => { draggedCard = card; card.classList.add('is-dragging'); event.dataTransfer.effectAllowed = 'move'; }); card.addEventListener('dragend', () => { card.classList.remove('is-dragging'); document.querySelectorAll('.drag-over').forEach(item => item.classList.remove('drag-over')); draggedCard = null; }); card.addEventListener('dragover', event => { if (!draggedCard || draggedCard === card) return; event.preventDefault(); card.classList.add('drag-over'); }); card.addEventListener('dragleave', () => card.classList.remove('drag-over')); card.addEventListener('drop', event => { event.preventDefault(); if (!draggedCard || draggedCard === card) return; card.parentNode.insertBefore(draggedCard, card); }); });
const sidebar = document.querySelector('.sidebar'); if (sidebar) { sidebar.addEventListener('wheel', (event) => { if (sidebar.scrollHeight <= sidebar.clientHeight) return; const nextTop = sidebar.scrollTop + event.deltaY; const maxTop = sidebar.scrollHeight - sidebar.clientHeight; if (nextTop > 0 && nextTop < maxTop) { event.preventDefault(); sidebar.scrollTop = nextTop; } }, { passive: false }); } window.addEventListener('resize', () => sync(model.state));
let last = performance.now(); function animate(now) { model.update((now - last) / 1000); last = now; sync(model.state); refreshControlState(); syncWorkspaceGraphs(); requestAnimationFrame(animate); } sync(model.state); refreshControlState(); requestAnimationFrame(animate);
